### ISSUE TITLE
Application crashes on my device

### ISSUE THREAD

**Issue by spinkham** [NitinJami/keychaineditor#1]
On my iPad 3 with iOS 8.1.3, keychain editor does not work in idb, and manual use crashes with the following message:

XXXXX:~ root# ./keychaineditor --action dump  
2015-05-11 10:24:44.560 keychaineditor[5248:519155] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: object cannot be nil (key: Data)'
**\* First throw call stack:
(0x2c5755f7 0x3a0c3c77 0x2c4927e5 0x48e40 0x49730 0x49dfc 0x3a65faaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

This was true for both the version idb installed and the fresh git checkout I compiled.

**Comment by smiles-css** [comment]
I am experiencing the same issue, iphone5 iOS 8.1.
2015-05-12 17:12:46.520 keychaineditor[1673:157929] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: object cannot be nil (key: Data)'
**\* First throw call stack:
(0x2268ec1f 0x2fe39c8b 0x225acab3 0xe3e3c 0xe472c 0xe4df8 0x303b9aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

--action min-dump does complete successfully and shows the same number of entries as keychain_dumper (70). However, this is only a fraction of the entries shown by keychain_dump and iphone-dataprotection KeychainViewer (117).

**Comment by smiles-css** [comment]
Just added a pull request to fix the exception. The utility still does not show all keychain entries, though.

**Comment by NitinJami** [comment]
Sorry folks, couldn't address this issue earlier. Was busy on other works. This should be fixed now.

**Comment by NitinJami** [comment]
@smiles-css My tool only supports generic passwords (genp) for now. Internet passwords (inetp), Certificates are left out. It may be possible that your count from keychainviewer shows for all of them included?
